# fly.toml app configuration file generated for server-wandering-fire-1875 on 2024-07-01T15:37:49+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-wandering-fire-1875'
primary_region = 'syd'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
  
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
  
  [[services.tcp_checks]]
    grace_period = "5s"
    interval = 10000
    timeout = 2000
